# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      run: |
        sudo apt-get install python3
        sudo apt-get install python3-pip
         
    - name: Install dependencies
      run: |
        ls
        python3 -m pip install --upgrade pip
        pip3 install nose2
        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        python3 nose2
